# Generated by Django 2.1.7 on 2019-03-03 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=150)),
                ('small_id', models.AutoField(primary_key=True, serialize=False)),
                ('identity', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('action', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url', models.URLField()),
                ('small_id', models.AutoField(primary_key=True, serialize=False)),
                ('identity', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UrlCategories',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('small_id', models.AutoField(primary_key=True, serialize=False)),
                ('identity', models.CharField(max_length=100)),
                ('reputation', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('router_ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='url_categories',
            field=models.ManyToManyField(to='portal.UrlCategories'),
        ),
        migrations.AddField(
            model_name='rule',
            name='urls',
            field=models.ManyToManyField(to='portal.Url'),
        ),
        migrations.AddField(
            model_name='policy',
            name='rules',
            field=models.ManyToManyField(to='portal.Rule'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Slot'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Venue'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Lecture'),
        ),
        migrations.AddField(
            model_name='course',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Policy'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='portal.Student'),
        ),
    ]
