# Generated by Django 2.1.7 on 2019-03-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='instructor',
        ),
    ]
